export enum Role {
  Visitor = 'Visitante',
  Student = 'Alumno',
  Instructor = 'Instructor',
  Institution = 'Institución',
  Admin = 'Administrador',
  SuperAdmin = 'Super Administrador',
}

export enum Permission {
  ViewCourses = 'view:courses',
  EnrollCourses = 'enroll:courses',
  CreateCourses = 'create:courses',
  EditCourses = 'edit:courses',
  DeleteCourses = 'delete:courses',
  ViewBiblioteca = 'view:biblioteca',
  DownloadBiblioteca = 'download:biblioteca',
  CreateBiblioteca = 'create:biblioteca',
  ViewCommunity = 'view:community',
  PostCommunity = 'post:community',
  ModerateCommunity = 'moderate:community',
  ViewInstitution = 'view:institution',
  ManageInstitution = 'manage:institution',
  ViewUsers = 'view:users',
  ManageUsers = 'manage:users',
  ViewReports = 'view:reports',
  ManageCertificates = 'manage:certificates',
  AccessAdmin = 'access:admin',
  AccessAI = 'access:ai',
}

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.Visitor]: [
    Permission.ViewCourses,
    Permission.ViewBiblioteca,
    Permission.ViewCommunity,
    Permission.ViewInstitution,
  ],
  [Role.Student]: [
    Permission.ViewCourses,
    Permission.EnrollCourses,
    Permission.ViewBiblioteca,
    Permission.DownloadBiblioteca,
    Permission.ViewCommunity,
    Permission.PostCommunity,
    Permission.ViewInstitution,
    Permission.AccessAI,
  ],
  [Role.Instructor]: [
    Permission.ViewCourses,
    Permission.EnrollCourses,
    Permission.CreateCourses,
    Permission.EditCourses,
    Permission.ViewBiblioteca,
    Permission.DownloadBiblioteca,
    Permission.CreateBiblioteca,
    Permission.ViewCommunity,
    Permission.PostCommunity,
    Permission.ModerateCommunity,
    Permission.ViewInstitution,
    Permission.ManageCertificates,
    Permission.AccessAI,
  ],
  [Role.Institution]: [
    Permission.ViewCourses,
    Permission.EnrollCourses,
    Permission.ViewBiblioteca,
    Permission.DownloadBiblioteca,
    Permission.ViewCommunity,
    Permission.PostCommunity,
    Permission.ViewInstitution,
    Permission.ManageInstitution,
    Permission.ViewReports,
    Permission.AccessAI,
  ],
  [Role.Admin]: Object.values(Permission),
  [Role.SuperAdmin]: Object.values(Permission),
};
